title: Nizar Benbouchta
#logo: /assets/img/logo.png
description: Hi, this is my personal website
show_downloads: true
linkedin_url: "https://www.linkedin.com/in/nizar-ben-bouchta-6a48a7146/"
theme: jekyll-theme-minimal
